    @startuml Manage Booking (PUT)

    header Booking Sequence Diagram
    footer Page %page% of %lastpage%
    title "Manage Booking (PUT)"

    participant "Client" as client
    participant "<<javaScript>>\n:server" as server
    participant "<<router>>\n:bookings" as routerBookings
    participant "<<middleware>>\n:auth" as middleware
    participant "<<controllers>>\n:bookings" as controllerBookings
    participant "<<model>>\n:Booking" as modelBooking
    database "<<MongoDB>>\n:Bookings" as BookingDatabase

    client-> server ++:req.put('/bookings/:id')
    server->routerBookings ++:app.use('/bookings',bookings)
    routerBookings -> middleware ++: protect(), authorize('admin','user')
    middleware -> controllerBookings ++:updateBooking()
    controllerBookings->modelBooking ++:findByIdAndUpdate(req.params.id,req.body)
    modelBooking ->BookingDatabase ++: BookingSchema
    BookingDatabase --> modelBooking --: booking
    controllerBookings <-- modelBooking --:booking
    controllerBookings->client --:response

    @enduml